influx:
  host: "http://127.0.0.1:8086"
  database: "database"
  user: ""
  password: ""
mysql:
  host: "127.0.0.1:3306"
  database: "bot"
  user: "bot"
  password: "secret"
discordtoken: "supersecret"
webbind: "0.0.0.0:8080"
cookiesecret: "ChangeMe!"
